## YAML Template.
language: php

 
php:
  - "5.6"
 
before_script:
#  - nvm install 4.2
#  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost
script:
  # Search for PHP syntax errors.
  # - find . \( -name '*.php' \) -exec php -lf {} \;
    phpunit
 
after_success:
  # Run npm build task.
#  - run npm dist